### PR TITLE
Add GitHub Actions CI/CD and badges

### PR DESCRIPTION
**Pull request by gordey4doronin**
Hello, here is a small and mostly useless PR. Hope you would enjoy it anyway. 😆 

## Changes

* Added Build/Release badges to the readme. It will be displayed in GitHub, and once you publish a new version, it will be also displayed in npmjs website.  Example below 👇 Screenshot 2020-08-21 at 12 38 53

* Added CI (Build) workflow to run tests automatically on 4 different versions of node (8,10,12,14).
* Added CD (Release) workflow, which will publish a package every time when release created. Just in case you would like to update it ever.
  * For CD step to work you need to add `npm_token` to your repo secrets https://github.com/ryancole/chunk/settings/secrets.
  * Safest approach would be **NOT** to store your **personal** token with access to all your packages (it's not accessible directly only by GitHub pipelines but who knows). Instead it would be safer to create/register additional account, say `ryancole-chunk-publisher-bot` and add it as a collaborator to the package in npmjs website and use its token here.
 * Added `.nvmrc` just in case. 🤷‍♂️ 
 * Added `.npmignore` to not publish `test` folder, right now it is published with the package itself.

## P.S.

I completely understand this package is too small to receive any updates in future.
It wasn't updated in last 6 years and most likely won't be updated as many years going further.
But the package has ~4k downloads weekly, so people use it.
So I decided to create that PR anyway.

The long story short is:
* I needed `chunk` functionality in few small projects.
* Lodash was not a choice as I had to keep code small, but `lodash` dependency is too huge to install, and even `lodash.chunk` has 500 lines of code cause they rely on their own implementation of `slice`/`toInteger`/`toFinite` etc.
* I would prefer to use native implementation in my particular case.
* Of course I could write a simple loop myself.
* However, I would need to copy-paste it across the projects (including copy-pasting the tests), or publish a package.
* So I started to create "yet another npm package for single purpose" and then I found your package.
* I checked the code and the tests and found it simple and useful for my purpose.
* But lack of CI/CD visibility confused me for a second.
* So I decided to fix that by creating this PR.

### CODE REVIEW

**Comment by gordey4doronin** [comment]
Oh, and you probably would need to enable GitHub Actions for your repository here https://github.com/ryancole/chunk/settings/actions, since it's an old repo it could be disabled by default. 🤔

**Comment by ryancole** [comment]
Haha awesome. Ill take a look here in a few minutes and enable the needed
features.

Thanks for the PR!

**Review by ryancole — APPROVED** [review]

**Comment by ryancole** [comment]
@gordey4doronin Looks good. I've never configured workflows, so this is new to me. Thanks for the PR!

**Comment by gordey4doronin** [comment]
@ryancole I've checked it too. Looks good indeed. Good call on updating old deps! 👍 And yes, latest `mocha` doesn't work well with node8, so completely fine to remove it. Well done. 💪

**Pull request merged**
